// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJaKqrkNewCCFjcKSenYB5T9VSkg3tI1E',
    appId: '1:929575619755:web:1399b20479d3764dc4fbee',
    messagingSenderId: '929575619755',
    projectId: 'daeufle',
    authDomain: 'daeufle.firebaseapp.com',
    storageBucket: 'daeufle.firebasestorage.app',
    measurementId: 'G-Q8056P5GDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_I-n0asE2dIPSOCC5MgLVCncZAAh4h24',
    appId: '1:929575619755:android:2ee7374c8abe9865c4fbee',
    messagingSenderId: '929575619755',
    projectId: 'daeufle',
    storageBucket: 'daeufle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMLDdd526LXiInDwKRsWHAgnAZKEzDpvk',
    appId: '1:929575619755:ios:147fea0d2321801bc4fbee',
    messagingSenderId: '929575619755',
    projectId: 'daeufle',
    storageBucket: 'daeufle.firebasestorage.app',
    iosBundleId: 'com.example.daeufle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMLDdd526LXiInDwKRsWHAgnAZKEzDpvk',
    appId: '1:929575619755:ios:147fea0d2321801bc4fbee',
    messagingSenderId: '929575619755',
    projectId: 'daeufle',
    storageBucket: 'daeufle.firebasestorage.app',
    iosBundleId: 'com.example.daeufle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJaKqrkNewCCFjcKSenYB5T9VSkg3tI1E',
    appId: '1:929575619755:web:c25097f4c44aaaeac4fbee',
    messagingSenderId: '929575619755',
    projectId: 'daeufle',
    authDomain: 'daeufle.firebaseapp.com',
    storageBucket: 'daeufle.firebasestorage.app',
    measurementId: 'G-5J3C0G6H0W',
  );
}
